-- ============================================
-- 001_esquema_inicial.sql
-- Crea la estructura base de ControlAprendices, ejectuar sql en una base de datos ya creada
-- ===


-- MySQL Script generated by MySQL Workbench
-- Thu Aug  6 18:38:31 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Rol` ;

CREATE TABLE IF NOT EXISTS `Rol` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Programa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Programa` ;

CREATE TABLE IF NOT EXISTS `Programa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ficha`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ficha` ;

CREATE TABLE IF NOT EXISTS `Ficha` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` INT(7) NOT NULL,
  `Programa_id` INT NOT NULL,
  `hora_entrada` TIME NULL,
  `hora_salida` TIME NULL,
  `instructor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Ficha_Programa1_idx` (`Programa_id` ASC) ,
  CONSTRAINT `fk_Ficha_Programa1`
    FOREIGN KEY (`Programa_id`)
    REFERENCES `Programa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuario` ;

CREATE TABLE IF NOT EXISTS `Usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `identificacion` BIGINT(20) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `Rol_id` INT NOT NULL,
  `Ficha_id` INT NULL,
  `codigo_llavero` VARCHAR(50) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  UNIQUE INDEX `identificacion_UNIQUE` (`identificacion` ASC) ,
  INDEX `fk_Usuario_Rol_idx` (`Rol_id` ASC) ,
  INDEX `fk_Usuario_Ficha1_idx` (`Ficha_id` ASC) ,
  CONSTRAINT `fk_Usuario_Rol`
    FOREIGN KEY (`Rol_id`)
    REFERENCES `Rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Ficha1`
    FOREIGN KEY (`Ficha_id`)
    REFERENCES `Ficha` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Asistencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Asistencia` ;

CREATE TABLE IF NOT EXISTS `Asistencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `hora_entrada` TIME NULL,
  `hora_salida` TIME NULL,
  `Usuario_id` INT NOT NULL,
  `estado` ENUM('Activo', 'Inactivo') NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Asistencia_Usuario1_idx` (`Usuario_id` ASC) ,
  CONSTRAINT `fk_Asistencia_Usuario1`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Excusa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Excusa` ;

CREATE TABLE IF NOT EXISTS `Excusa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `motivo` TEXT NOT NULL,
  `evidencia` VARCHAR(255) NULL,
  `Usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Excusa_Usuario1_idx` (`Usuario_id` ASC) ,
  CONSTRAINT `fk_Excusa_Usuario1`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Estado_Excusa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Estado_Excusa` ;

CREATE TABLE IF NOT EXISTS `Estado_Excusa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `respuesta` TEXT NULL,
  `estado` ENUM('Aprobada', 'Rechazada') NULL,
  `Excusa_id` INT NOT NULL,
  `Usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Estado_Excusa_Excusa1_idx` (`Excusa_id` ASC) ,
  INDEX `fk_Estado_Excusa_Usuario1_idx` (`Usuario_id` ASC) ,
  CONSTRAINT `fk_Estado_Excusa_Excusa1`
    FOREIGN KEY (`Excusa_id`)
    REFERENCES `Excusa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estado_Excusa_Usuario1`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
